# Generated by Django 2.2.2 on 2019-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('date_adm', models.DateTimeField(auto_now_add=True)),
                ('id_no', models.IntegerField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
